feat: update schemas
MapColonies/polygon-parts-manager pull request #1
Opened 2023-09-19 05:40 UTC by ronenkapelian

Adding more columns to polygon parts table

* imageName,  ProductType
* adding insert query with geojson geom (insted of wkt)

* update fullScheme creation script

| Question                | Answer                                                                          |
| ---------------- | -------------------------------------------------------------------------- |
| Bug fix         | ✖                                                                        |
| New feature     | ✔                                                                       |
| Breaking change | ✖                                                                        |
| Deprecations    | ✖                                                                        |
| Documentation   | ✖                                                                        |
| Tests added     | ✖                                                                        |
| Chore            | ✖                                                                       |

2023-09-19 05:57 UTC, asafMasa requested changes
👍

2023-09-19 05:57 UTC, asafMasa commented on src/DAL/migration/FullSchema.sql
> +    "productType" text COLLATE pg_catalog."default" NOT NULL DEFAULT 'orthophotoBest'::text,
the default should be in code and not in scheme

2023-09-19 05:57 UTC, asafMasa commented on src/DAL/migration/insertDataExample.sql
> +	VALUES ('1328b7b4-e4e5-4d7f-a00f-087a2fab6309', 'MosaicBest', 'orthophoto', '1.0', '2022-10-10 11:30:30', '2022-10-10 11:30:30', 0.000000335276126861572, 0.072, 5, 5, 10, '1, 2, 3', 'world', 5, 'som
add space at the end of the file

2023-09-20 13:58 UTC, ronenkapelian commented on src/DAL/migration/insertDataExample.sql
> +	VALUES ('1328b7b4-e4e5-4d7f-a00f-087a2fab6309', 'MosaicBest', 'orthophoto', '1.0', '2022-10-10 11:30:30', '2022-10-10 11:30:30', 0.000000335276126861572, 0.072, 5, 5, 10, '1, 2, 3', 'world', 5, 'som
added

2023-09-20 15:00 UTC, asafMasa approved these changes

2023-09-21 06:07 UTC, merged