fix: connection manager
MapColonies/polygon-parts-manager pull request #14
Opened 2024-10-21 14:02 UTC by vitaligi

* fix connection manager initialization and DI
* fix resources cleanup on termination
* fix type definition

| Question                | Answer                                                                          |
| ---------------- | -------------------------------------------------------------------------- |
| Bug fix         | ✔                                                                        |
| New feature     | ✖                                                                        |
| Breaking change | ✖                                                                        |
| Deprecations    | ✖                                                                        |
| Documentation   | ✖                                                                        |
| Tests added     | ✖                                                                        |
| Chore            | ✖                                                                       |

2024-10-28 13:53 UTC, CL-SHLOMIKONCHA requested changes
Please check the case of reconnection

2024-10-28 13:53 UTC, CL-SHLOMIKONCHA commented on src/common/connectionManager.ts
Please change to our log convension ({msg: 'bla bla'}), exmaple:
![image](https://github.com/user-attachments/assets/951b0098-6e89-42fb-88a4-f13844b570dd)

2024-10-28 14:14 UTC, vitaligi commented on src/common/connectionManager.ts
done

2024-10-28 15:51 UTC, vitaligi commented
> Please check the case of reconnection

checked manually TypeORM is able to reconnect

2024-10-30 12:17 UTC, CL-SHLOMIKONCHA approved these changes

2024-10-30 12:17 UTC, merged